<?php

namespace Database\Seeders;

use App\Models\InterventionDay;
use App\Models\MedicalCenter;
use Illuminate\Database\Seeder;

class RoadmapAndMedicalSeeder extends Seeder
{
    public function run(): void
    {
        // 1. Dữ liệu 30 ngày can thiệp
        $days = [
            // Tuần 1: Detox màn hình & Kết nối mắt
            [
                'day_number' => 1,
                'week_number' => 1,
                'title' => 'Ngày 1: Chiến dịch tắt màn hình & Dọn dẹp không gian tĩnh',
                'goal' => 'Ngắt kích thích 1 chiều từ tivi, điện thoại; tạo sự chú ý vào âm thanh con người.',
                'activity_name' => 'Chiến dịch "Cất điện thoại vào hộp bí mật"',
                'instructions' => 'Tắt tivi cả ngày, cất điện thoại ngoài tầm với của bé. Khi bé đòi, đưa một món đồ chơi vật lý phát ra tiếng leng keng hoặc bóng tròn rực rỡ để đánh lạc hướng.',
                'target_words' => 'Cất, Đi chơi, Ôi kìa!',
                'parent_tip' => 'Bé có thể khóc và cáu kỉnh trong 1-2 ngày đầu vì thiếu dopamime từ màn hình. Cha mẹ hãy kiên nhẫn ôm ấp, vỗ về và kiên định không nhượng bộ.',
                'icon' => '📵',
                'duration_minutes' => 30,
            ],
            [
                'day_number' => 2,
                'week_number' => 1,
                'title' => 'Ngày 2: Trò chơi Ú Oà tăng giao tiếp mắt',
                'goal' => 'Kích thích bé nhìn thẳng vào mắt cha mẹ và bật cười hưởng ứng.',
                'activity_name' => 'Ú Oà với khăn mỏng nhiều màu sắc',
                'instructions' => 'Dùng khăn mỏng che mặt mẹ, hỏi: "Mẹ đâu rồi ta? Một... hai... ba..." rồi hất khăn ra hô to "Ú... OÀ!". Làm đi làm lại 5-10 lần.',
                'target_words' => 'Ú, Oà, Ba, Mẹ',
                'parent_tip' => 'Trước khi mở khăn, dừng lại 3 giây nhìn con để con chờ đợi. Sự háo hức kích hoạt phản xạ biểu cảm nét mặt.',
                'icon' => '🙈',
                'duration_minutes' => 20,
            ],
            [
                'day_number' => 3,
                'week_number' => 1,
                'title' => 'Ngày 3: Hạ thấp tầm mắt ngang tầm con',
                'goal' => 'Thiết lập tư thế giao tiếp đúng chuẩn âm ngữ trị liệu.',
                'activity_name' => 'Nằm sấp hoặc ngồi bệt đối diện bé',
                'instructions' => 'Khi nói chuyện hoặc chơi với con, luôn ngồi xổm hoặc nằm sấp để mặt bạn ngang bằng mặt con, cách khoảng 30-40cm. Không đứng từ trên cao nói vọng xuống.',
                'target_words' => 'Nhìn mẹ, Bé ơi, Lại đây',
                'parent_tip' => 'Trẻ chậm nói cần nhìn rõ khẩu hình khuôn miệng của bạn thì mới bắt chước cử động môi được.',
                'icon' => '👀',
                'duration_minutes' => 25,
            ],
            [
                'day_number' => 4,
                'week_number' => 1,
                'title' => 'Ngày 4: Trò chơi soi gương và biểu cảm ngộ nghĩnh',
                'goal' => 'Giúp con nhận thức bản thân và kích hoạt cơ mặt.',
                'activity_name' => 'Cùng soi gương lớn',
                'instructions' => 'Bế bé trước gương lớn, chỉ vào gương: "Ai đây? Bé Bắp này!", sau đó mẹ làm các động tác chu môi, phồng má, lè lưỡi và rủ con làm theo.',
                'target_words' => 'Mũi, Mắt, Miệng, Aaa',
                'parent_tip' => 'Gương tạo ra phản xạ thị giác thú vị giúp bé không còn cảm thấy áp lực phải nói.',
                'icon' => '🪞',
                'duration_minutes' => 20,
            ],
            [
                'day_number' => 5,
                'week_number' => 1,
                'title' => 'Ngày 5: Gọi tên và phản hồi chạm nhẹ',
                'goal' => 'Rèn luyện phản xạ quay đầu ngay khi nghe thấy tên mình.',
                'activity_name' => 'Gọi tên kết hợp chạm vai ấm áp',
                'instructions' => 'Đứng cách bé 1 mét, gọi tên con rõ ràng 1 lần kèm tông giọng vui vẻ. Nếu con chưa quay lại, bước tới chạm nhẹ vào vai, cúi xuống mỉm cười: "Mẹ gọi con này!".',
                'target_words' => 'Dạ, Ơi, Tên của bé',
                'parent_tip' => 'Không gọi tên dồn dập 5-7 lần liên tiếp như tiếng súng liên thanh, điều này khiến não bé sinh ra phản xạ "lờ đi" âm thanh đó.',
                'icon' => '🔔',
                'duration_minutes' => 20,
            ],
            [
                'day_number' => 6,
                'week_number' => 1,
                'title' => 'Ngày 6: Massage cơ mặt và vành môi',
                'goal' => 'Thư giãn cơ mặt và kích thích các đầu mút dây thần kinh vùng miệng.',
                'activity_name' => 'Massage "Mưa rơi tí tách trên má"',
                'instructions' => 'Dùng các đầu ngón tay gõ nhẹ nhàng lên má con theo nhịp: "Tí tách tí tách", sau đó vuốt nhẹ quanh vành môi con theo chiều kim đồng hồ.',
                'target_words' => 'Mưa, Tí tách, Thích quá',
                'parent_tip' => 'Làm khi con vừa tắm xong hoặc đang thư giãn nằm nghe mẹ hát ru.',
                'icon' => '💆',
                'duration_minutes' => 15,
            ],
            [
                'day_number' => 7,
                'week_number' => 1,
                'title' => 'Ngày 7: Tổng kết tuần 1 & Đọc sách lật mở tương tác',
                'goal' => 'Đánh giá lại mức độ giao tiếp mắt sau 1 tuần cai thiết bị số.',
                'activity_name' => 'Đọc sách Ehon / Sách vải sờ chạm',
                'instructions' => 'Cầm cuốn sách có các miếng lật mở, cầm tay con lật miếng bìa và reo lên: "Bí mật gì đây?... A, bạn thỏ trắng!".',
                'target_words' => 'Mở, Đóng, Thỏ, Wow',
                'parent_tip' => 'Không cần đọc hết chữ trong sách, chỉ cần gọi tên đồ vật và tạo ra các âm thanh cảm thán ngạc nhiên.',
                'icon' => '📖',
                'duration_minutes' => 25,
            ],

            // Tuần 2: Âm thanh tượng thanh
            [
                'day_number' => 8,
                'week_number' => 2,
                'title' => 'Ngày 8: Kích hoạt âm môi với Bong bóng xà phòng',
                'goal' => 'Rèn luyện luồng hơi thở và phát âm các âm /b/, /m/, /p/.',
                'activity_name' => 'Thổi bóng và nổ "BÙM!"',
                'instructions' => 'Thổi chùm bóng xà phòng bay lên, giơ ngón tay chọc vỡ từng quả bóng và hô to: "BÙM!... BÙM!". Cầm tay con cùng chọc vỡ.',
                'target_words' => 'Bóng, Bùm, Bay, Nữa',
                'parent_tip' => 'Giữ ống thổi gần miệng của bạn trước khi thổi quả tiếp theo, chờ con phát ra âm "Bù" hoặc "Bó" rồi mới thổi.',
                'icon' => '🫧',
                'duration_minutes' => 20,
            ],
            [
                'day_number' => 9,
                'week_number' => 2,
                'title' => 'Ngày 9: Thế giới con vật - Bắt chước âm thanh động vật',
                'goal' => 'Khai thác âm thanh tượng thanh tự nhiên nhất.',
                'activity_name' => 'Nông trại vui vẻ',
                'instructions' => 'Cầm mô hình hoặc tranh ảnh con chó: "Con chó sủa gâu gâu", con bò: "Ùm bòooo", con mèo: "Meo meo". Nhại âm kéo dài.',
                'target_words' => 'Gâu gâu, Meo meo, Ùm bò',
                'parent_tip' => 'Trẻ con luôn phát âm tiếng con vật trước khi nói được từ ngữ phức tạp. Hãy coi tiếng kêu con vật là từ vựng thực thụ!',
                'icon' => '🐶',
                'duration_minutes' => 25,
            ],
            [
                'day_number' => 10,
                'week_number' => 2,
                'title' => 'Ngày 10: Âm thanh xe cộ & Đồ chơi chuyển động',
                'goal' => 'Kích thích âm rung môi và bật hơi.',
                'activity_name' => 'Đoàn tàu và xe cứu hỏa',
                'instructions' => 'Đẩy chiếc ô tô chạy trên sàn: "Brum brum... Bim bim!", đẩy đoàn tàu: "Xình xịch... Tu tu!". Khi xe dừng: "Kétttt!".',
                'target_words' => 'Brum, Bim bim, Tu tu, Dừng',
                'parent_tip' => 'Chơi đẩy qua đẩy lại giữa mẹ và con để rèn luyện thói quen "đến lượt tôi - đến lượt bạn" (Turn-taking).',
                'icon' => '🚗',
                'duration_minutes' => 25,
            ],
            [
                'day_number' => 11,
                'week_number' => 2,
                'title' => 'Ngày 11: Bài tập thổi hơi vận động vòm họng',
                'goal' => 'Tăng sức mạnh cho cơ vành môi và cơ hoành.',
                'activity_name' => 'Thổi chong chóng và thổi vụn giấy',
                'instructions' => 'Xé những mẩu giấy màu nhỏ đặt lên lòng bàn tay, ghé miệng thổi phù một cái cho giấy bay tung tóe: "Phùuuu!". Rủ con cùng thổi.',
                'target_words' => 'Phù, Bay, Thổi',
                'parent_tip' => 'Rất nhiều trẻ chậm nói do cơ quan phát âm (vành môi, lưỡi) bị nhược cơ, chưa biết cách điều hòa luồng khí.',
                'icon' => '💨',
                'duration_minutes' => 20,
            ],
            [
                'day_number' => 12,
                'week_number' => 2,
                'title' => 'Ngày 12: Nhún nhảy theo bài hát đồng dao có nhịp điệu',
                'goal' => 'Cảm thụ nhịp điệu âm tiết tiếng Việt.',
                'activity_name' => 'Kéo cưa lừa xẻ / Tập tầm vông',
                'instructions' => 'Hai mẹ con cầm tay nhau đung đưa theo nhịp điệu bài "Kéo cưa lừa xẻ, ông thợ nào khỏe, về ăn cơm vua...". Đến từ cuối cùng giật mạnh tạo tiếng cười.',
                'target_words' => 'Kéo, Thợ, Cơm, Vua',
                'parent_tip' => 'Tiếng Việt là ngôn ngữ đơn âm tiết có thanh điệu. Nhịp điệu đồng dao giúp tai con bắt nhịp cực kỳ nhanh.',
                'icon' => '🎵',
                'duration_minutes' => 20,
            ],
            [
                'day_number' => 13,
                'week_number' => 2,
                'title' => 'Ngày 13: Trò chơi trốn tìm đồ vật giấu dưới gối',
                'goal' => 'Phát triển nhận thức tính vĩnh cửu của đồ vật (Object permanence).',
                'activity_name' => 'Món đồ chơi biến mất đi đâu?',
                'instructions' => 'Giấu chiếc xe ô tô dưới chiếc khăn hoặc gối ngay trước mắt con: "Ủa, xe đi đâu rồi ta?". Chờ con lật khăn lên: "Aaa! Thấy rồi!".',
                'target_words' => 'Mất, Đâu, Thấy, Aaa',
                'parent_tip' => 'Kỹ năng nhận thức liên quan trực tiếp đến khả năng gọi tên sự vật trong não bộ.',
                'icon' => '🔍',
                'duration_minutes' => 20,
            ],
            [
                'day_number' => 14,
                'week_number' => 2,
                'title' => 'Ngày 14: Đánh giá mốc 2 tuần & Lặp lại các âm con thích nhất',
                'goal' => 'Củng cố các âm thanh con đã bắt đầu phát ra trong tuần.',
                'activity_name' => 'Nhật ký âm thanh của bé',
                'instructions' => 'Ghi lại 3-5 âm thanh con hay phát ra nhất trong 2 tuần qua. Tạo ra một trò chơi tổng hợp sử dụng lại toàn bộ các âm đó.',
                'target_words' => 'Ôn tập toàn bộ âm tuần 1 & 2',
                'parent_tip' => 'Hãy khen ngợi con nhiệt tình mỗi khi con chịu phát ra bất kỳ âm thanh nào, dù còn ngọng nghịu.',
                'icon' => '🌟',
                'duration_minutes' => 30,
            ],

            // Tuần 3: Vốn từ nhu cầu & Chỉ tay
            [
                'day_number' => 15,
                'week_number' => 3,
                'title' => 'Ngày 15: Kỹ thuật tạo "Tình huống có vấn đề" (Communication Temptation)',
                'goal' => 'Buộc bé phải chủ động mở miệng thay vì được đáp ứng sẵn.',
                'activity_name' => 'Đặt món đồ yêu thích trong hộp trong suốt',
                'instructions' => 'Bỏ chiếc bánh hoặc ô tô bé thích vào một hộp nhựa trong suốt đậy nắp chặt, để trước mặt bé. Con nhìn thấy nhưng không mở được, buộc phải quay sang nhờ mẹ.',
                'target_words' => 'Mở, Giúp, Cho, Mẹ ơi',
                'parent_tip' => 'Nếu mọi thứ trong nhà đều được cha mẹ dâng tận miệng, đứa trẻ sẽ hoàn toàn KHÔNG CÓ NHU CẦU phải nói.',
                'icon' => '📦',
                'duration_minutes' => 25,
            ],
            [
                'day_number' => 16,
                'week_number' => 3,
                'title' => 'Ngày 16: Dạy chỉ tay bằng ngón trỏ (Pointing)',
                'goal' => 'Hình thành cử chỉ giao tiếp quan trọng nhất trước khi nói.',
                'activity_name' => 'Chỉ tay chọn món đồ ăn vặt',
                'instructions' => 'Cầm 2 món đồ trên 2 tay (ví dụ: hộp sữa và quả chuối): "Con chọn sữa hay chuối?". Cầm tay bé gập các ngón lại, xòe ngón trỏ chỉ vào món con muốn: "Chuối này!".',
                'target_words' => 'Này, Kia, Sữa, Chuối',
                'parent_tip' => 'Trẻ biết chỉ tay thường sẽ bật âm chỉ sau đó 2 - 4 tuần. Chỉ tay là cây cầu nối trực tiếp đến lời nói.',
                'icon' => '👉',
                'duration_minutes' => 20,
            ],
            [
                'day_number' => 17,
                'week_number' => 3,
                'title' => 'Ngày 17: Dạy từ chối lịch sự ("Không" & Lắc đầu)',
                'goal' => 'Giúp con bày tỏ cảm xúc phủ định mà không cần ăn vạ.',
                'activity_name' => 'Món đồ con không thích',
                'instructions' => 'Đưa cho con một món đồ con không thích: "Bé có ăn rau không?". Khi con né tránh, mẹ lắc đầu nói mẫu: "Không! Con không ăn".',
                'target_words' => 'Không, Hết, Thôi',
                'parent_tip' => 'Học nói từ "Không" giúp giảm 60% các cơn ăn vạ gào khóc ở trẻ 18-36 tháng.',
                'icon' => '🙅',
                'duration_minutes' => 20,
            ],
            [
                'day_number' => 18,
                'week_number' => 3,
                'title' => 'Ngày 18: Kỹ thuật đưa ra 2 lựa chọn (Choice Making)',
                'goal' => 'Khuyến khích con đưa ra quyết định bằng ngôn ngữ.',
                'activity_name' => 'Chọn áo mặc / Chọn cốc uống nước',
                'instructions' => 'Mỗi khi làm gì, đưa ra 2 lựa chọn: "Con muốn mặc áo đỏ hay áo xanh?", "Uống nước cốc gấu hay cốc mèo?". Đưa từng đồ vật gần miệng bạn khi đọc tên.',
                'target_words' => 'Đỏ, Xanh, Gấu, Mèo',
                'parent_tip' => 'Không hỏi câu hỏi mở chung chung như "Con muốn mặc cái gì?", trẻ chậm nói sẽ không biết cách trả lời.',
                'icon' => '👕',
                'duration_minutes' => 20,
            ],
            [
                'day_number' => 19,
                'week_number' => 3,
                'title' => 'Ngày 19: Giờ ăn vui vẻ - Tắm ngôn ngữ cảm giác',
                'goal' => 'Liên kết từ ngữ với vị giác và nhiệt độ.',
                'activity_name' => 'Mô tả bữa ăn',
                'instructions' => 'Khi xúc cơm: "Cơm nóng... Thổi phù phù nào... Măm măm ngon quá!". Khi uống canh: "Ngọt thế... Canh ngọt".',
                'target_words' => 'Nóng, Ngon, Ngọt, Canh',
                'parent_tip' => 'Tuyệt đối không bật tivi cho con xem để dụ ăn cơm. Giờ ăn là thời gian vàng để dạy từ vựng vị giác.',
                'icon' => '🥣',
                'duration_minutes' => 30,
            ],
            [
                'day_number' => 20,
                'week_number' => 3,
                'title' => 'Ngày 20: Giờ tắm rộn ràng - Bộ phận cơ thể',
                'goal' => 'Học tên các bộ phận cơ thể qua xúc giác nước ấm.',
                'activity_name' => 'Kỳ cọ tay chân trong bồn tắm',
                'instructions' => 'Khi tắm, kỳ cọ tay: "Kỳ tay sạch nào... Tay đâu?... Tay đây!". Kỳ bụng: "Bụng tròn xoe... Xoa bụng".',
                'target_words' => 'Tay, Chân, Bụng, Nước',
                'parent_tip' => 'Nước ấm kích thích cảm giác xúc giác giúp não bộ dễ tiếp thu từ vựng vị trí cơ thể.',
                'icon' => '🛁',
                'duration_minutes' => 25,
            ],
            [
                'day_number' => 21,
                'week_number' => 3,
                'title' => 'Ngày 21: Ôn tập tuần 3 - Kỹ thuật mở rộng từ (+1 Word Expansion)',
                'goal' => 'Nâng cấp từ đơn lên cụm từ.',
                'activity_name' => 'Nói theo kiểu Mẹ + 1',
                'instructions' => 'Nếu con chỉ vào quả bóng nói "Bóng", mẹ đáp lại ngay: "Đúng rồi, bóng tròn!" hoặc "Ném bóng!".',
                'target_words' => 'Bóng tròn, Xe to, Mẹ bế',
                'parent_tip' => 'Luôn nói dài hơn con đúng 1 từ để làm khuôn mẫu cho não bộ của con học hỏi mà không bị quá tải.',
                'icon' => '🧩',
                'duration_minutes' => 25,
            ],

            // Tuần 4: Ghép từ đôi & Mở rộng
            [
                'day_number' => 22,
                'week_number' => 4,
                'title' => 'Ngày 22: Ghép từ đôi chỉ hành động (Động từ + Danh từ)',
                'goal' => 'Hình thành câu ghép 2 từ cơ bản.',
                'activity_name' => 'Chơi giả vờ cho búp bê ăn',
                'instructions' => 'Cầm thìa đút cho gấu bông: "Gấu ăn... Ăn cơm", "Búp bê ngủ... Đi ngủ". Hướng dẫn con làm theo.',
                'target_words' => 'Ăn cơm, Đi ngủ, Uống sữa',
                'parent_tip' => 'Trò chơi đóng vai giả vờ (Pretend play) là bước phát triển trí tuệ biểu tượng rất quan trọng.',
                'icon' => '🧸',
                'duration_minutes' => 30,
            ],
            [
                'day_number' => 23,
                'week_number' => 4,
                'title' => 'Ngày 23: Dạo chơi công viên & Khám phá thế giới thực',
                'goal' => 'Đổi mới môi trường giao tiếp ngoài trời.',
                'activity_name' => 'Đi dạo hít thở và chỉ lá cây',
                'instructions' => 'Dắt tay con ra sân hoặc công viên: "Nhìn kìa, bông hoa màu vàng", "Chiếc lá rơi... Bay bay...". Cùng con nhặt lá.',
                'target_words' => 'Hoa, Lá, Cây, Chim',
                'parent_tip' => 'Không gian mở thiên nhiên kích thích mọi giác quan giúp trẻ vui vẻ và dễ bật âm tự nhiên nhất.',
                'icon' => '🌳',
                'duration_minutes' => 40,
            ],
            [
                'day_number' => 24,
                'week_number' => 4,
                'title' => 'Ngày 24: Trò chơi xếp chồng cốc và phá đổ ("1, 2, 3... ĐỔ!")',
                'goal' => 'Rèn luyện sự kiên nhẫn và từ ngữ cao trào.',
                'activity_name' => 'Xây tháp cao',
                'instructions' => 'Xếp các khối hộp hoặc cốc nhựa chồng lên nhau thật cao: "Một... hai... ba..." rồi đẩy đổ: "ĐỔ RỒI! Ầm!".',
                'target_words' => 'Một, Hai, Ba, Đổ',
                'parent_tip' => 'Cảm xúc bùng nổ khi tháp đổ là khoảnh khắc con dễ hét to và phát ra âm thanh cao trào nhất.',
                'icon' => '🧱',
                'duration_minutes' => 20,
            ],
            [
                'day_number' => 25,
                'week_number' => 4,
                'title' => 'Ngày 25: Luyện khẩu lệnh 2 bước',
                'goal' => 'Nâng cao khả năng hiểu ngôn ngữ tiếp nhận.',
                'activity_name' => 'Nhiệm vụ nhí của con',
                'instructions' => 'Giao nhiệm vụ: "Con nhặt bóng, bỏ vào giỏ cho mẹ", "Lấy dép, đi lại đây". Kèm điệu bộ chỉ dẫn.',
                'target_words' => 'Bỏ vào, Cất đi, Lại đây',
                'parent_tip' => 'Hiểu tốt mệnh lệnh 2 bước là nền tảng để trẻ bắt đầu nói câu ghép phức tạp hơn.',
                'icon' => '🧺',
                'duration_minutes' => 25,
            ],
            [
                'day_number' => 26,
                'week_number' => 4,
                'title' => 'Ngày 26: Gọi điện thoại giả vờ cho người thân',
                'goal' => 'Tập phản xạ chào hỏi và đối thoại.',
                'activity_name' => 'Chiếc điện thoại đồ chơi',
                'instructions' => 'Dùng điện thoại đồ chơi áp vào tai: "A lô... Ai đấy?... A lô bà nội ạ!". Sau đó đưa cho bé: "Con a lô bà đi!".',
                'target_words' => 'A lô, Bà ơi, Con đây',
                'parent_tip' => 'Điện thoại đồ chơi (không có màn hình điện tử) là công cụ tuyệt vời để kích hoạt phản xạ đối đáp 2 chiều.',
                'icon' => '☎️',
                'duration_minutes' => 20,
            ],
            [
                'day_number' => 27,
                'week_number' => 4,
                'title' => 'Ngày 27: Trò chơi giấu tay sau lưng & Hát đếm',
                'goal' => 'Tăng tương tác nhịp điệu và ghi nhớ vị trí.',
                'activity_name' => 'Đôi bàn tay tí hon',
                'instructions' => 'Giấu 2 tay sau lưng: "Tay đẹp đâu rồi?... A, đây rồi!". Cùng xòe tay ra và vỗ tay hoan hô.',
                'target_words' => 'Đây, Đâu, Hoan hô',
                'parent_tip' => 'Động tác vận động tinh (xòe ngón tay) liên kết chặt chẽ với vùng điều khiển ngôn ngữ trên vỏ não.',
                'icon' => '👐',
                'duration_minutes' => 20,
            ],
            [
                'day_number' => 28,
                'week_number' => 4,
                'title' => 'Ngày 28: Kể chuyện trước giờ đi ngủ (Bedtime Routine)',
                'goal' => 'Lắng nghe giọng nói ấm áp của cha mẹ để xoa dịu thần kinh.',
                'activity_name' => 'Kể chuyện ngày hôm nay của con',
                'instructions' => 'Tắt đèn vàng ấm, nằm cạnh ôm con và kể lại một ngày: "Hôm nay bé đi công viên... bé ăn chuối ngon... bé ngủ ngoan nhé".',
                'target_words' => 'Yêu con, Ngủ ngoan, Chúc ngủ ngon',
                'parent_tip' => 'Giọng nói trầm ấm của cha mẹ lúc chuẩn bị ngủ giúp củng cố ký ức từ vựng dài hạn trong não bộ trẻ.',
                'icon' => '🌙',
                'duration_minutes' => 20,
            ],
            [
                'day_number' => 29,
                'week_number' => 4,
                'title' => 'Ngày 29: Buổi tiệc âm thanh cùng cả gia đình',
                'goal' => 'Mở rộng giao tiếp với nhiều thành viên (Bố, Mẹ, Anh/Chị, Ông/Bà).',
                'activity_name' => 'Cả nhà cùng chơi trốn tìm',
                'instructions' => 'Cả nhà cùng tham gia, thay phiên nhau gọi tên bé và trốn sau rèm cửa hoặc sau ghế sofa để bé đi tìm.',
                'target_words' => 'Bố, Mẹ, Bà, Anh, Chị',
                'parent_tip' => 'Sự tham gia đồng bộ của cả gia đình tạo ra môi trường ngôn ngữ phong phú và sinh động nhất.',
                'icon' => '🎉',
                'duration_minutes' => 30,
            ],
            [
                'day_number' => 30,
                'week_number' => 4,
                'title' => 'Ngày 30: Đánh giá tổng kết 30 ngày & Lộ trình tiếp theo',
                'goal' => 'Kiểm tra lại toàn bộ tiến bộ của con và quyết định bước can thiệp tiếp theo.',
                'activity_name' => 'Làm lại bài trắc nghiệm sàng lọc',
                'instructions' => 'Cho con làm lại bài test sàng lọc trên website Mầm Ngôn Ngữ để so sánh điểm số và số lượng cờ đỏ trước và sau 30 ngày.',
                'target_words' => 'Tổng kết & Tự hào về con',
                'parent_tip' => 'Nếu con có tiến bộ rõ rệt: tiếp tục duy trì! Nếu sau 30 ngày tương tác chuẩn mực mà con không hề tiến bộ hoặc có dấu hiệu thoái lui: hãy đưa con đi khám chuyên khoa ngay lập tức.',
                'icon' => '🏆',
                'duration_minutes' => 30,
            ],
        ];

        foreach ($days as $day) {
            InterventionDay::updateOrCreate(['day_number' => $day['day_number']], $day);
        }

        // 2. Dữ liệu cơ sở y tế / Bệnh viện uy tín
        $centers = [
            [
                'name' => 'Bệnh viện Nhi Đồng 1 - Khoa Tâm lý & Vật lý trị liệu',
                'city' => 'TP. Hồ Chí Minh',
                'address' => '341 Sư Vạn Hạnh, Phường 10, Quận 10, TP. Hồ Chí Minh',
                'phone' => '(028) 3927 1119',
                'website' => 'https://nhidong.org.vn',
                'specialty' => 'Đánh giá chậm nói, Tự kỷ, Âm ngữ trị liệu, Thính học',
                'description' => 'Trung tâm đầu ngành tại miền Nam chuyên thăm khám, can thiệp sớm các rối loạn phát triển ngôn ngữ, giao tiếp ở trẻ em.',
                'booking_tip' => 'Nên đăng ký khám trực tuyến qua tổng đài hoặc website từ trước 1-2 tuần để tránh xếp hàng đông.',
                'is_verified' => true,
                'order_index' => 1,
            ],
            [
                'name' => 'Bệnh viện Nhi Đồng 2 - Phòng khám Tâm lý',
                'city' => 'TP. Hồ Chí Minh',
                'address' => '14 Lý Tự Trọng, Phường Bến Nghé, Quận 1, TP. Hồ Chí Minh',
                'phone' => '(028) 3829 5723',
                'website' => 'https://benhviennhi.org.vn',
                'specialty' => 'Tâm lý lâm sàng, Chậm phát triển ngôn ngữ, Rối loạn phổ tự kỷ',
                'description' => 'Quy tụ đội ngũ chuyên gia tâm lý và bác sĩ thần kinh nhi giàu kinh nghiệm thực hiện test Denver II, Vineland, M-CHAT.',
                'booking_tip' => 'Khoa Tâm lý có dịch vụ khám theo hẹn, có thể gọi hotline đặt trước để được khám đúng khung giờ.',
                'is_verified' => true,
                'order_index' => 2,
            ],
            [
                'name' => 'Bệnh viện Nhi Trung Ương - Khoa Tâm bệnh & Thần kinh',
                'city' => 'Hà Nội',
                'address' => '18/879 La Thành, Phường Láng Thượng, Quận Đống Đa, Hà Nội',
                'phone' => '(024) 6273 8532',
                'website' => 'https://benhviennhitrunguong.gov.vn',
                'specialty' => 'Chẩn đoán chuyên sâu Tự kỷ, Chậm nói, Tăng động giảm chú ý, Đo thính lực ABR',
                'description' => 'Bệnh viện tuyến cuối lớn nhất miền Bắc với quy trình đánh giá đa chuyên khoa bài bản: Thần kinh - Tâm lý - Thính học.',
                'booking_tip' => 'Có thể đặt khám tại Trung tâm Quốc tế hoặc khoa Khám chữa bệnh theo yêu cầu để giảm thời gian chờ.',
                'is_verified' => true,
                'order_index' => 3,
            ],
            [
                'name' => 'Bệnh viện Bạch Mai - Viện Sức khỏe Tâm thần',
                'city' => 'Hà Nội',
                'address' => '78 Giải Phóng, Phường Phương Mai, Quận Đống Đa, Hà Nội',
                'phone' => '(024) 3869 3731',
                'website' => 'https://bachmai.gov.vn',
                'specialty' => 'Tâm thần học Nhi, Rối loạn ngôn ngữ, Can thiệp hành vi',
                'description' => 'Đơn vị uy tín hàng đầu trong lĩnh vực tâm thần học và đánh giá các rối loạn phát triển thần kinh ở trẻ em.',
                'booking_tip' => 'Đến sớm vào buổi sáng để hoàn tất quy trình khám và làm các bài test trắc nghiệm tâm lý trong ngày.',
                'is_verified' => true,
                'order_index' => 4,
            ],
            [
                'name' => 'Bệnh viện Phụ sản - Nhi Đà Nẵng',
                'city' => 'Đà Nẵng',
                'address' => '402 Lê Văn Hiến, Phường Khuê Mỹ, Quận Ngũ Hành Sơn, Đà Nẵng',
                'phone' => '(0236) 3957 777',
                'website' => 'https://phusannhidanang.org.vn',
                'specialty' => 'Khoa Phục hồi chức năng, Can thiệp âm ngữ, Thần kinh nhi',
                'description' => 'Địa chỉ thăm khám và can thiệp phát triển ngôn ngữ, vận động hàng đầu cho trẻ em khu vực Miền Trung - Tây Nguyên.',
                'booking_tip' => 'Liên hệ khoa Khám bệnh hoặc Phục hồi chức năng để đăng ký gói đánh giá phát triển định kỳ.',
                'is_verified' => true,
                'order_index' => 5,
            ],
            [
                'name' => 'Bệnh viện Nhi Đồng Cần Thơ',
                'city' => 'Cần Thơ',
                'address' => 'Số 04 Đường 3/2, Phường An Bình, Quận Ninh Kiều, Cần Thơ',
                'phone' => '(0292) 3748 350',
                'website' => 'https://nhidongcantho.org.vn',
                'specialty' => 'Phục hồi chức năng nhi, Khám tâm lý và sàng lọc chậm nói',
                'description' => 'Trung tâm nhi khoa lớn nhất vùng Đồng bằng sông Cửu Long với các chương trình tập luyện âm ngữ trị liệu cho trẻ nhỏ.',
                'booking_tip' => 'Đăng ký tại quầy tiếp đón khu khám chuyên khoa nhi.',
                'is_verified' => true,
                'order_index' => 6,
            ],
        ];

        foreach ($centers as $center) {
            MedicalCenter::updateOrCreate(['name' => $center['name']], $center);
        }
    }
}
